services:
  web:
    build: .
    command: gunicorn insuradmin_backend.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/InsurAdmin
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
    
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  pgadmin:
    container_name: pgadmin4_insuradmin_box
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"

volumes:
  postgres_data: