# Generated by Django 5.0.4 on 2024-05-10 04:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_of_business', models.CharField(blank=True, default='Other', max_length=254, null=True)),
                ('policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('insurer', models.CharField(blank=True, max_length=100, null=True)),
                ('policy_holder', models.CharField(blank=True, max_length=254, null=True)),
                ('commencement_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('policy_maturity', models.DateField(blank=True, null=True)),
                ('payment_frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('insurance_policy', models.FileField(blank=True, upload_to='insurance_policies')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('special_status', 'Can see own insurances')],
                'indexes': [models.Index(fields=['id'], name='id_index')],
            },
        ),
    ]
